#!/bin/bash

# Change name of the file to variables, before running deploy
SCRIPTDIR=/etc/apcupsd
MAILSCRIPT=mail
JSONIFY=status_tojson

export MJ_APIKEY_PUBLIC=""
export MJ_APIKEY_PRIVATE=""
export SENDER_MAIL=""
export RECIPIENT_MAIL=""
export RECIPIENT_NAME="John Doe"

arr=()
while IFS=  read -r line; do
    echo $line
    arr+=( "$(echo $line | cut -d':' -f2- | xargs)" )
done < <(apcaccess status | grep -E -i '^(STATUS|BCHARGE)')

STATUS=${arr[0]}
BCHARGE=${arr[1]}

echo $STATUS
echo $BCHARGE

${SCRIPTDIR}/${MAILSCRIPT} "$STATUS" "$BCHARGE"
${SCRIPTDIR}/${JSONIFY}
